### ISSUE TITLE
can't run on android 7 (EABI=arm64-v8a)

### ISSUE THREAD

**Issue by ksatalsin** [amosyuen/FFmpegVideoRecorder#1]
Hi !

er: report state:1 event type:2 pid:26047 uid:10133 pkg:null to pid: 1013
library "/system/lib64/libdl.so" ("/system/lib64/libdl.so") needed or dlopened by "/vendor/lib64/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.sad.android.dev-1/lib/arm64:/data/app/com.sad.android.dev-1/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.sad.android.dev"]

      ]
mempoolcfg case CLEAR_ALL, virtual void android::MTMemoryPool::MemHandler::handleMessage(const android::Message &)
library "/system/lib64/libavutil.so" ("/product/lib64/libavutil.so") needed or dlopened by "/vendor/lib64/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.sad.android.dev-1/lib/arm64:/data/app/com.sad.android.dev-1/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.sad.android.dev"]
library "/product/lib64/libavutil.so" ("/product/lib64/libavutil.so") needed or dlopened by "/vendor/lib64/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.sad.android.dev-1/lib/arm64:/data/app/com.sad.android.dev-1/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.sad.android.dev"]
library "/system/lib64/libavutil.so" ("/product/lib64/libavutil.so") needed or dlopened by "/vendor/lib64/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.sad.android.dev-1/lib/arm64:/data/app/com.sad.android.dev-1/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.sad.android.dev"]
ecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sad.android.dev-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sad.android.dev-1/lib/arm64, /data/app/com.sad.android.dev-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "libjniavutil.so"
 at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.String) (Runtime.java:989)
 at void java.lang.System.loadLibrary(java.lang.String) (System.java:1533)
 at java.lang.String org.bytedeco.javacpp.Loader.loadLibrary(java.net.URL[], java.lang.String) (Loader.java:784)
 at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class, java.util.Properties, boolean) (Loader.java:586)
 at java.lang.String org.bytedeco.javacpp.Loader.load() (Loader.java:503)
 at void org.bytedeco.javacpp.avutil.<clinit>() (avutil.java:10)
 at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
 at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
 at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class, java.util.Properties, boolean) (Loader.java:558)
 at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class) (Loader.java:519)
 at void com.amosyuen.videorecorder.util.FFmpegFrameRecorder.tryLoad() (FFmpegFrameRecorder.java:197)
 at void com.amosyuen.videorecorder.util.FFmpegFrameRecorder.<clinit>() (FFmpegFrameRecorder.java:218)
 at com.amosyuen.videorecorder.util.FFmpegFrameRecorder com.amosyuen.videorecorder.util.Util.createFrameRecorder(java.io.File, com.amosyuen.videorecorder.util.FFmpegRecorderParams) (Util.java:22)
 at java.lang.Exception com.amosyuen.videorecorder.FFmpegRecorderActivity$SaveVideoTask.doInBackground(java.lang.Object[]) (FFmpegRecorderActivity.java:601)
 at java.lang.Object com.amosyuen.videorecorder.FFmpegRecorderActivity$SaveVideoTask.doInBackground(java.lang.Object[]) (FFmpegRecorderActivity.java:567)
 at java.lang.Object android.os.AsyncTask$2.call() (AsyncTask.java:316)
 at void java.util.concurrent.FutureTask.run() (FutureTask.java:237)
 at void android.os.AsyncTask$SerialExecutor$1.run() (AsyncTask.java:255)
 at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133)
 at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607)
 at void java.lang.Thread.run() (Thread.java:774)
sed by: java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libavutil.so" needed or dlopened by "/vendor/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
 at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.String) (Runtime.java:994)
 at void java.lang.System.loadLibrary(java.lang.String) (System.java:1533)
 at java.lang.String org.bytedeco.javacpp.Loader.loadLibrary(java.net.URL[], java.lang.String) (Loader.java:784)
 at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class, java.util.Properties, boolean) (Loader.java:577)
 at java.lang.String org.bytedeco.javacpp.Loader.load() (Loader.java:503)
 at void org.bytedeco.javacpp.avutil.<clinit>() (avutil.java:10)
 at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
 at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
 at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class, java.util.Properties, boolean) (Loader.java:558)
 at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class) (Loader.java:519)
 at void com.amosyuen.videorecorder.util.FFmpegFrameRecorder.tryLoad() (FFmpegFrameRecorder.java:197)
 at void com.amosyuen.videorecorder.util.FFmpegFrameRecorder.<clinit>() (FFmpegFrameRecorder.java:218)
 at com.amosyuen.videorecorder.util.FFmpegFrameRecorder com.amosyuen.videorecorder.util.Util.createFrameRecorder(java.io.File, com.amosyuen.videorecorder.util.FFmpegRecorderParams) (Util.java:22)
 at java.lang.Exception com.amosyuen.videorecorder.FFmpegRecorderActivity$SaveVideoTask.doInBackground(java.lang.Object[]) (FFmpegRecorderActivity.java:601)
 at java.lang.Object com.amosyuen.videorecorder.FFmpegRecorderActivity$SaveVideoTask.doInBackground(java.lang.Object[]) (FFmpegRecorderActivity.java:567)
 at java.lang.Object android.os.AsyncTask$2.call() (AsyncTask.java:316)
 at void java.util.concurrent.FutureTask.run() (FutureTask.java:237)
 at void android.os.AsyncTask$SerialExecutor$1.run() (AsyncTask.java:255)
 at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133)
 at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607)
 at void java.lang.Thread.run() (Thread.java:774)
sed by: java.lang.UnsatisfiedLinkError: dlopen failed: library "/product/lib64/libavutil.so" needed or dlopened by "/vendor/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
 at void java.lang.Runtime.load0(java.lang.Class, java.lang.String) (Runtime.java:914)
 at void java.lang.System.load(java.lang.String) (System.java:1508)
 at java.lang.String org.bytedeco.javacpp.Loader.loadLibrary(java.net.URL[], java.lang.String) (Loader.java:767)
 at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class, java.util.Properties, boolean) (Loader.java:577)
 at java.lang.String org.bytedeco.javacpp.Loader.load() (Loader.java:503)
 at void org.bytedeco.javacpp.avutil.<clinit>() (avutil.java:10)
 at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
 at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
 at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class, java.util.Properties, boolean) (Loader.java:558)
 at java.lang.String org.bytedeco.javacpp.Loader.load(java.lang.Class) (Loader.java:519)
 at void com.amosyuen.videorecorder.util.FFmpegFrameRecorder.tryLoad() (FFmpegFrameRecorder.java:197)
 at void com.amosyuen.videorecorder.util.FFmpegFrameRecorder.<clinit>() (FFmpegFrameRecorder.java:218)
 at com.amosyuen.videorecorder.util.FFmpegFrameRecorder com.amosyuen.videorecorder.util.Util.createFrameRecorder(java.io.File, com.amosyuen.videorecorder.util.FFmpegRecorderParams) (Util.java:22)
 at java.lang.Exception com.amosyuen.videorecorder.FFmpegRecorderActivity$SaveVideoTask.doInBackground(java.lang.Object[]) (FFmpegRecorderActivity.java:601)
 at java.lang.Object com.amosyuen.videorecorder.FFmpegRecorderActivity$SaveVideoTask.doInBackground(java.lang.Object[]) (FFmpegRecorderActivity.java:567)
 at java.lang.Object android.os.AsyncTask$2.call() (AsyncTask.java:316)
 at void java.util.concurrent.FutureTask.run() (FutureTask.java:237)
 at void android.os.AsyncTask$SerialExecutor$1.run() (AsyncTask.java:255)
 at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133)
 at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607)
 at void java.lang.Thread.run() (Thread.java:774)
 
FATAL EXCEPTION: AsyncTask #3

                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:330)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:774)
                                                    Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sad.android.dev-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sad.android.dev-1/lib/arm64, /data/app/com.sad.android.dev-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "libjniavutil.so"
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                       at java.lang.System.loadLibrary(System.java:1533)
                                                       at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:784)
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:586)
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:503)
                                                       at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.Class.forName(Class.java:400)
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:558)
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:519)
                                                       at com.amosyuen.videorecorder.util.FFmpegFrameRecorder.tryLoad(FFmpegFrameRecorder.java:197)
                                                       at com.amosyuen.videorecorder.util.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:218)
                                                       at com.amosyuen.videorecorder.util.Util.createFrameRecorder(Util.java:22)
                                                       at com.amosyuen.videorecorder.FFmpegRecorderActivity$SaveVideoTask.doInBackground(FFmpegRecorderActivity.java:601)
                                                       at com.amosyuen.videorecorder.FFmpegRecorderActivity$SaveVideoTask.doInBackground(FFmpegRecorderActivity.java:567)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:316)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:774) 
                                                    Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libavutil.so" needed or dlopened by "/vendor/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:994)
                                                       at java.lang.System.loadLibrary(System.java:1533)
                                                       at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:784)
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:577)
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:503) 
                                                       at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10) 
                                                       at java.lang.Class.classForName(Native Method) 
                                                       at java.lang.Class.forName(Class.java:400) 
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:558) 
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:519) 
                                                       at com.amosyuen.videorecorder.util.FFmpegFrameRecorder.tryLoad(FFmpegFrameRecorder.java:197) 
                                                       at com.amosyuen.videorecorder.util.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:218) 
                                                       at com.amosyuen.videorecorder.util.Util.createFrameRecorder(Util.java:22) 
                                                       at com.amosyuen.videorecorder.FFmpegRecorderActivity$SaveVideoTask.doInBackground(FFmpegRecorderActivity.java:601) 
                                                       at com.amosyuen.videorecorder.FFmpegRecorderActivity$SaveVideoTask.doInBackground(FFmpegRecorderActivity.java:567) 
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:316) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:774) 
                                                    Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "/product/lib64/libavutil.so" needed or dlopened by "/vendor/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
                                                       at java.lang.Runtime.load0(Runtime.java:914)
                                                       at java.lang.System.load(System.java:1508)
                                                       at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:767)
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:577) 
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:503) 
                                                       at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10) 
                                                       at java.lang.Class.classForName(Native Method) 
                                                       at java.lang.Class.forName(Class.java:400) 
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:558) 
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:519) 
                                                       at com.amosyuen.videorecorder.util.FFmpegFrameRecorder.tryLoad(FFmpegFrameRecorder.java:197) 
                                                       at com.amosyuen.videorecorder.util.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:218) 
                                                       at com.amosyuen.videorecorder.util.Util.createFrameRecorder(Util.java:22) 
                                                       at com.amosyuen.videorecorder.FFmpegRecorderActivity$SaveVideoTask.doInBackground(FFmpegRecorderActivity.java:601) 
                                                       at com.amosyuen.videorecorder.FFmpegRecorderActivity$SaveVideoTask.doInBackground(FFmpegRecorderActivity.java:567) 
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:316) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:774)

**Comment by amosyuen** [comment]
So javacv and ffmpeg libraries don't have arm64 native libraries, only armv5 and armv7 libraries. Likely your binary includes some native library with arm64. Unfortunately Android can't use both 32 bit and 64 bit libraries at the same time, so it won't load the 32 bit native libraries if you include 64 bit libraries.

You can change gradle to exclude x64 dependencies. You can do something like what [Realm recommends for this problem](https://realm.io/docs/java/latest/#couldnt-load-librealm-jniso). Do something like:

```
android {
    //...
    packagingOptions {
        exclude "lib/arm64-v8a/**"
    }
    //...
}
```

**Comment by ksatalsin** [comment]
Thanks!  You've made a good job!
