### ISSUE TITLE
Start failed-19(when recording in portrait mode at 640*480)

### ISSUE THREAD

**Issue by rishabhsri20** [amosyuen/FFmpegVideoRecorder#15]
start 0 m_rotation
02-23 19:26:03.442 20351-20351/com.amosyuen.videorecorder.demo E/MediaRecorder: start failed: -19
02-23 19:26:03.451 20351-20351/com.amosyuen.videorecorder.demo E/MediaClipsRecorder: Error starting recorder
                                                                                     java.lang.RuntimeException: start failed.
                                                                                         at android.media.MediaRecorder.native_start(Native Method)
                                                                                         at android.media.MediaRecorder.start(MediaRecorder.java:1084)
                                                                                         at com.amosyuen.videorecorder.recorder.MediaClipsRecorder.start(MediaClipsRecorder.java:152)
                                                                                         at com.amosyuen.videorecorder.activity.FFmpegRecorderActivity.startRecording(FFmpegRecorderActivity.java:434)
                                                                                         at com.amosyuen.videorecorder.activity.FFmpegRecorderActivity.onTouch(FFmpegRecorderActivity.java:521)
                                                                                         at android.view.View.dispatchTouchEvent(View.java:11772)
                                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                         at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:446)
                                                                                         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1848)
                                                                                         at android.app.Activity.dispatchTouchEvent(Activity.java:3315)
                                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                                         at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:408)
                                                                                         at android.view.View.dispatchPointerEvent(View.java:12015)
                                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4855)
                                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4638)
                                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4169)
                                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4222)
                                                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4188)
                                                                                         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4315)
                                                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4196)
                                                                                         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4372)
                                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4169)
                                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4222)
                                                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4188)
                                                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4196)
                                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4169)
                                                                                         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6743)
                                                                                         at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6717)
                                                                                         at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6663)
                                                                                         at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6846)
                                                                                         at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
                                                                                         at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                         at android.os.MessageQueue.next(MessageQueue.java:325)
                                                                                         at android.os.Looper.loop(Looper.java:142)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
02-23 19:26:03.455 20351-20351/com.amosyuen.videorecorder.demo E/FFmpegRecorderActivity: Media recorder error
                                                                                         java.lang.RuntimeException: start failed.
                                                                                             at android.media.MediaRecorder.native_start(Native Method)
                                                                                             at android.media.MediaRecorder.start(MediaRecorder.java:1084)
                                                                                             at com.amosyuen.videorecorder.recorder.MediaClipsRecorder.start(MediaClipsRecorder.java:152)
                                                                                             at com.amosyuen.videorecorder.activity.FFmpegRecorderActivity.startRecording(FFmpegRecorderActivity.java:434)
                                                                                             at com.amosyuen.videorecorder.activity.FFmpegRecorderActivity.onTouch(FFmpegRecorderActivity.java:521)
                                                                                             at android.view.View.dispatchTouchEvent(View.java:11772)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2593)
                                                                                             at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:446)
                                                                                             at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1848)
                                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:3315)
                                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                                             at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:408)
                                                                                             at android.view.View.dispatchPointerEvent(View.java:12015)
                                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4855)
                                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4638)
                                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4169)
                                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4222)
                                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4188)
                                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4315)
                                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4196)
                                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4372)
                                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4169)
                                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4222)
                                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4188)
                                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4196)
                                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4169)
                                                                                             at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6743)
                                                                                             at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6717)
                                                                                             at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6663)
                                                                                             at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6846)
                                                                                             at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
                                                                                             at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                             at android.os.MessageQueue.next(MessageQueue.java:325)
                                                                                             at android.os.Looper.loop(Looper.java:142)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by rishabhsri20** [comment]
Added details.

**Comment by valterh4ck3r** [comment]
Same problem.
