### ISSUE TITLE
Error when pause and play again in camera

### ISSUE THREAD

**Issue by juanlabrador** [amosyuen/FFmpegVideoRecorder#18]
07-21 13:47:24.851 30258-30258/com.amosyuen.videorecorder.demo E/InputEventReceiver: Exception dispatching input event.
07-21 13:47:24.851 30258-30258/com.amosyuen.videorecorder.demo E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
07-21 13:47:24.855 30258-30258/com.amosyuen.videorecorder.demo E/MessageQueue-JNI: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:121)
        at com.amosyuen.videorecorder.util.Util.setMediaRecorderInteractionParams(Util.java:65)
        at com.amosyuen.videorecorder.activity.FFmpegRecorderActivity.configureMediaRecorder(FFmpegRecorderActivity.java:247)
        at com.amosyuen.videorecorder.recorder.MediaClipsRecorder.start(MediaClipsRecorder.java:130)
        at com.amosyuen.videorecorder.activity.FFmpegRecorderActivity.startRecording(FFmpegRecorderActivity.java:433)
        at com.amosyuen.videorecorder.activity.FFmpegRecorderActivity.onTouch(FFmpegRecorderActivity.java:520)
        at android.view.View.dispatchTouchEvent(View.java:10035)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:417)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3198)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:379)
        at android.view.View.dispatchPointerEvent(View.java:10261)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4500)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4365)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4051)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3932)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4108)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3932)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6309)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6283)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6244)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6415)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6239)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    	at com.
07-21 13:47:24.855 30258-30258/com.amosyuen.videorecorder.demo D/AndroidRuntime: Shutting down VM
07-21 13:47:24.857 30258-30258/com.amosyuen.videorecorder.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amosyuen.videorecorder.demo, PID: 30258
    java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:121)
        at com.amosyuen.videorecorder.util.Util.setMediaRecorderInteractionParams(Util.java:65)
        at com.amosyuen.videorecorder.activity.FFmpegRecorderActivity.configureMediaRecorder(FFmpegRecorderActivity.java:247)
        at com.amosyuen.videorecorder.recorder.MediaClipsRecorder.start(MediaClipsRecorder.java:130)
        at com.amosyuen.videorecorder.activity.FFmpegRecorderActivity.startRecording(FFmpegRecorderActivity.java:433)
        at com.amosyuen.videorecorder.activity.FFmpegRecorderActivity.onTouch(FFmpegRecorderActivity.java:520)
        at android.view.View.dispatchTouchEvent(View.java:10035)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:417)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3198)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:379)
        at android.view.View.dispatchPointerEvent(View.java:10261)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4500)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4365)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4051)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3932)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4108)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3932)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6309)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6283)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6244)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6415)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6239)
07-21 13:47:24.858 30258-30258/com.amosyuen.videorecorder.demo E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

## Steps to Reproduce the Problem

1. It has defaults values, only I changed max recording to 90 seconds and max file size to 5 mb.
2. When launch video, play and recording normal, loose finger and stopped recorder, good. Later press again and crashed.

## Specifications

- Version: Api 27
- Platform: 
- Subsystem:

**Comment by KarimRedaHassan** [comment]
I also have the exact same issue
